// prettier-ignore
// const products = [
//   {
//     "_id": "1",
//     "name": "Airpods Wireless Bluetooth Headphones",
//     "image": "/images/airpods.jpg",
//     "description": "Bluetooth technology lets you connect it with compatible devices wirelessly High-Quality AAC audio offers immense experience Built-in microphone allows you take calls while working",
//     "brand": "Apple",
//     "category": "Electronics",
//     "price": 89.99,
//     "coutInStock": 0,
//     "rating": 4.5,
//     "numReviews": 12,
//   },
//   {
//     "_id": "2",
//     "name": "IPhone 11 Pro 256GB memory",
//     "image": "/images/phone.jpg",
//     "description": "Bluetooth technology lets you connect it with compatible devices wirelessly High-Quality AAC audio offers immense experience Built-in microphone allows you take calls while working",
//     "brand": "Apple",
//     "category": "Electronics",
//     "price": 599.99,
//     "coutInStock": 7,
//     "rating": 4.0,
//     "numReviews": 8,
//   },
//   {
//     "_id": "3",
//     "name": "Cannon EOS 80D DSR Camera",
//     "image": "/images/camera.jpg",
//     "description": "Bluetooth technology lets you connect it with compatible devices wirelessly High-Quality AAC audio offers immense experience Built-in microphone allows you take calls while working",
//     "brand": "Cannon",
//     "category": "Eelectronics",
//     "price": 929.99,
//     "coutInStock": 5,
//     "rating": 4.3,
//     "numReviews": 12,
//   },
//   {
//     "_id": "4",
//     "name": "Sony Playstation 4 Pro White Version",
//     "image": "/images/playstation.jpg",
//     "description": "The ultimate entertainment center starts with PLaystation. Wether you are into faming, HD movies, television or music",
//     "brand": "Sony",
//     "category": "Eelectronics",
//     "price": 399.99,
//     "coutInStock": 11,
//     "rating": 5,
//     "numReviews": 12,
//   },
//   {
//     "_id": "5",
//     "name": "Logitech G-Series gaming Mouse",
//     "image": "/images/mouse.jpg",
//     "description": "Get a better handle on your games with this Ligoitech Lighstick gaming mouse. Th esicth proggamable buttons allow customization for a smooth playing experience.",
//     "brand": "Logitech",
//     "category": "Eelectronics",
//     "price": 49.99,
//     "coutInStock": 7,
//     "rating": 3.5,
//     "numReviews": 10,
//   },
//   {
//     "_id": "6",
//     "name": "Amazon Echo Dot 23rd Generation",
//     "image": "/images/alexa.jpg",
//     "description": "Meet Echo Dot, our most popular smart speaker with a fabric design. It is our most compact smart speaker taht fits perfectly into small spaces.",
//     "brand": "Amazon",
//     "category": "Eelectronics",
//     "price": 29.99,
//     "coutInStock": 0,
//     "rating": 0,
//     "numReviews": 12,
//   },
// ];

// export default products;
