# Generated by Django 4.1.3 on 2022-11-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename__id_order_id_rename__id_orderitem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='id',
            new_name='_id',
        ),
    ]
